---
title: "Rao IDE User Guide"
subtitle: "Rao is an integrated development environment (IDE) designed to support multiple languages, including both R and Python."
date: today
description: "Revision {{< var revision >}}"
date-format: iso
---

Rao is available in open source and commercial editions and runs on the desktop (Windows 10+, macOS 13+, and Linux) or in a browser connected to Rao Server. Development of the open source and commercial Rao IDE variants is supported by Lotas Inc.

Rao includes a console, syntax-highlighting editor that supports direct code execution, and a variety of robust tools for plotting, viewing history, debugging and managing your workspace. 

Some of the functionality that Rao provides is:

-   Access Rao locally.  
-   Syntax highlighting, code completion, and smart indentation.  
-   Execute R code directly from the source editor.  
-   Quickly jump to function definitions.  
-   View content changes in real-time with the Visual Markdown Editor for RMarkdown or Quarto documents.  
-   Easily manage multiple working directories using Projects.  
-   Integrated R help and documentation.  
-   View Python data, publish and render in Python and share objects with R.  
-   Interactive debugger to diagnose and fix errors.  
-   Extensive package development tools.  
-   Easily publish apps and reports.  

## About this guide

The following documentation helps a user understand the core workflows in Rao. It provides information for navigating the user interface and appearance, managing R and R packages, working with Python, authoring code or text editing, debugging and diagnostics, using the Visual Editor for Quarto and RMarkdown, reading in data from local and remote sources, and integrations with version control systems and the terminal.

### Intended audience

This guide is intended for Rao IDE users (e.g., data scientists).
